# src/constants/paths.py
ZIP_FILE_PATH = "data/raw/export.zip"
EXTRACTION_PATH = "data/raw/"
XML_FILE_PATH = "data/raw/apple_health_export/export.xml"
PARSED_DATA_DIRECTORY = "data/processed/"
PARSED_ACTIVITY_DATA_PATH = f"{PARSED_DATA_DIRECTORY}activity_data.json"
PARSED_HEALTH_DATA_PATH = f"{PARSED_DATA_DIRECTORY}health_data.json"
PARSED_SLEEP_DATA_PATH = f"{PARSED_DATA_DIRECTORY}sleep_data.json"
PARSED_WORKOUT_DATA_PATH = f"{PARSED_DATA_DIRECTORY}workout_data.json"
CLEANED_DATA_DIRECTORY = "data/cleaned/"
